In [2]:
import tensorflow as tf
import numpy as np

Creating Tensors

In [3]:
tensor_0d = tf.constant(12,dtype=tf.dtypes.int32)
tensor_0d

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [4]:
tensor_1d = tf.constant([1,2,3,4,5],dtype=tf.dtypes.int32)
tensor_1d

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [5]:
tensor_2d = tf.constant([[1,2,3],[4,5,6]])
tensor_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
tensor_3d = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor_3d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

Dimensions

In [7]:
tensor_0d.shape

TensorShape([])

In [8]:
tensor_1d.shape

TensorShape([5])

In [9]:
tensor_2d.shape

TensorShape([2, 3])

In [10]:
tensor_3d.shape

TensorShape([2, 2, 3])

Casting Tensors

In [13]:
t_1 = tf.constant([1,2.,3],dtype=tf.dtypes.float32)
t1_casted = tf.cast(t_1,dtype=tf.dtypes.int32)
t1_casted

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

Numpy array to Tensor

In [14]:
np_array = np.array([1,2,3,4,5])
t_2 = tf.convert_to_tensor(np_array)
t_2

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

tf.eye()

In [18]:
t_3 = tf.eye(7,5,dtype=tf.dtypes.int32)
t_3

<tf.Tensor: shape=(7, 5), dtype=int32, numpy=
array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

tf.fill()

In [19]:
t_4 = tf.fill([5,6],10)
t_4

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]], dtype=int32)>

tf.ones()

In [21]:
t_5 = tf.ones([4,5],dtype=tf.dtypes.int32)
t_5

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

tf.ones_like()

In [22]:
t_6 = tf.ones_like(t_4)
t_6

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)>

tf.zeros()

In [23]:
t_7 = tf.zeros([4,3])
t_7

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

tf.shape()

In [24]:
tf.shape(t_7)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>

tf.rank()

In [25]:
tf.rank(t_7)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

tf.size()

In [26]:
tf.size(t_7)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

Random Tensors

In [27]:
t_8 = tf.random.normal([5,6],6,2)
t_8

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[ 9.818577 ,  7.210592 ,  8.789107 , 11.887361 ,  5.7409153,
         7.5998373],
       [ 9.045275 ,  2.496441 ,  4.954213 ,  6.772224 ,  8.01807  ,
         5.991993 ],
       [ 9.213833 ,  5.9991455,  4.424883 ,  5.8526297,  8.032241 ,
         7.7109866],
       [ 2.1252182,  5.955906 ,  7.291724 ,  3.5785744,  1.9694109,
         7.541971 ],
       [ 8.706277 ,  9.325851 ,  3.7819116,  5.2761254,  7.945703 ,
         5.625662 ]], dtype=float32)>

In [28]:
tf.random.uniform([3,4],1,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2.0483093, 3.182022 , 2.3010464, 8.10358  ],
       [8.192817 , 9.039517 , 3.221442 , 7.9916477],
       [1.9681637, 7.067599 , 7.559783 , 8.711261 ]], dtype=float32)>

In [34]:
tf.random.set_seed(5)
t_9 = tf.random.uniform([2,2],3,8,seed=10)
t_9

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.4582448, 7.783611 ],
       [3.1486468, 6.6170716]], dtype=float32)>