**Ragged Tensor**

In [ ]:
import tensorflow as tf
tensor_2d = [[1,2,3],[4],[5,6],[7,8,9,10]]
tensor_ragged = tf.ragged.constant(tensor_2d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 3], [4], [5, 6], [7, 8, 9, 10]]>


In [ ]:
tensor_ragged.shape

TensorShape([4, None])

BooleanMask

In [ ]:
mask = [[True,False,True],[False,False,True],[True,True,False]]
data = [[1,2,3],[4,5,6],[7,8,9]]
tf.ragged.boolean_mask(data,mask)

<tf.RaggedTensor [[1, 3], [6], [7, 8]]>

from_row_lengths()

In [ ]:
values = [1,2,3,4,5,6,7,8,9,10]
row_lengths = [1,5,0,3,1]
tf.RaggedTensor.from_row_lengths(values,row_lengths)

<tf.RaggedTensor [[1], [2, 3, 4, 5, 6], [], [7, 8, 9], [10]]>

**SparseTensors**

In [ ]:
tensor_sparse = tf.sparse.SparseTensor(indices=[[1,1],[3,4]],values=[11,56],dense_shape=[6,6])
tensor_sparse

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([6 6], shape=(2,), dtype=int64))

To dense tensor

In [ ]:
tensor_dense = tf.sparse.to_dense(tensor_sparse)
tensor_dense

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>