# String Tensors

In [4]:
import tensorflow as tf
tensor_string = tf.constant(["hello","World"])
print(tensor_string)
print(tensor_string.numpy())

tf.Tensor([b'hello' b'World'], shape=(2,), dtype=string)
[b'hello' b'World']


In [10]:
t1 = tf.constant(["My name"," is ","ganesh"])
t2 = tf.strings.join(t1,separator="")
print(t2)
print(t2.numpy())

tf.Tensor(b'My name is ganesh', shape=(), dtype=string)
b'My name is ganesh'


In [9]:
strings = tf.constant(["ganesh","suvarna","ram","Lak"])
lengths = tf.strings.length(strings)
print(lengths)
print(lengths.numpy())

tf.Tensor([6 7 3 3], shape=(4,), dtype=int32)
[6 7 3 3]


In [12]:
strings_lower = tf.strings.lower(["CamelCase","ALLCAPS"])
print(strings_lower)
print(strings_lower.numpy())

tf.Tensor([b'camelcase' b'allcaps'], shape=(2,), dtype=string)
[b'camelcase' b'allcaps']


# Variables

In [15]:
x = tf.constant(9.0)
x_var = tf.Variable(x,name='var1',trainable=False)
print(x_var)
print(x_var.numpy())

<tf.Variable 'var1:0' shape=() dtype=float32, numpy=9.0>
9.0


In [16]:
v = tf.Variable([1,2])
v.assign([6,5])
print(v.numpy())


[6 5]


In [19]:
v.assign_add([1,6])
print(v.numpy())
v.assign_sub([1,1])
print(v.numpy())

[ 8 17]
[ 7 16]


# Controlling Devices

In [22]:
with tf.device('CPU:0'):
  x1 = tf.Variable([1,2])
  x2 = tf.Variable([2,3])
with tf.device('GPU:0'):
  x3 = x1 + x2
print(x3)
print(x3.numpy())

tf.Tensor([3 5], shape=(2,), dtype=int32)
[3 5]
